settings_location = "../embedding/settings.json"
embeddings_folder = "../embeddings/"
matrix_train_location = "../data/training_matrices/train_matrix.npz"
matrix_test_location = "../data/training_matrices/test_matrix.npz"
zero_matrix_train_location = "../data/training_matrices/zero_embedding_train_matrix.npz"
zero_matrix_full_train_location = "../data/training_matrices/zero_embedding_full_train_matrix.npz"
replaced_zero_matrix_train_location = "../data/training_matrices/replaced_zero_embedding_train_matrix.npz"
replaced_zero_matrix_full_train_location = "../data/training_matrices/replaced_zero_embedding_full_train_matrix.npz"
zero_matrix_test_location = "../data/training_matrices/zero_embedding_test_matrix.npz"
replaced_zero_matrix_test_location = "../data/training_matrices/replaced_zero_embedding_test_matrix.npz"
stanford_embedding_location = "../embeddings/glove.twitter.27B.200d.txt"
bert_matrix_train_location = "../data/training_matrices/bert_embedding_train_matrix.npz"
bert_matrix_train_location2 = "../data/training_matrices/bert_embedding_train_matrix2.npz"
roberta_matrix_train_location = "../data/training_matrices/roberta_embedding_train_matrix.npz"
roberta_full_matrix_train_location = "../data/training_matrices/roberta_full_embedding_train_matrix.npz"
embedding_dim = 200

